### ISSUE TITLE
升级到v0.27.1后报错 slice bounds out of range [128:119]

### ISSUE THREAD

**Issue by kakuilan** [emmansun/gmsm#226]
升级到v0.27.1后报错：
```txt
panic: runtime error: slice bounds out of range [128:119]

goroutine 1 [running]:
github.com/emmansun/gmsm/sm3.kdfBy8(0xc000f9b4b8, 0x477, 0x24)
	/var/www/test/vendor/github.com/emmansun/gmsm/sm3/kdf_mult8_amd64.go:79 +0x985
github.com/emmansun/gmsm/sm3.kdf(0xc000f9b4b8?, 0xc000f9b328?, 0x40?)
	/var/www/test/vendor/github.com/emmansun/gmsm/sm3/kdf_amd64.go:11 +0x2b
github.com/emmansun/gmsm/sm3.(*digest).Kdf(0xc000f9b4b8, {0xc000f9b328?, 0xc000002c80?, 0x700?}, 0x477)
	/var/www/test/vendor/github.com/emmansun/gmsm/sm3/sm3.go:223 +0x8f
github.com/emmansun/gmsm/sm3.Kdf(...)
	/var/www/test/vendor/github.com/emmansun/gmsm/sm3/sm3.go:243
github.com/emmansun/gmsm/sm2.decryptSM2EC(0xc0007a4af0, 0xc000e6c6c0, {0xc000bf1c00?, 0x0?, 0xc0018d9350?}, 0xc000f7841c?)
	/var/www/test/vendor/github.com/emmansun/gmsm/sm2/sm2.go:426 +0x2d1
github.com/emmansun/gmsm/sm2.decrypt(0xc000e6c6c0, {0xc000bf1c00, 0x4d8, 0x700}, 0xba4cdfe)
	/var/www/test/vendor/github.com/emmansun/gmsm/sm2/sm2.go:404 +0xd8
github.com/emmansun/gmsm/sm2.(*PrivateKey).Decrypt(0xc000f78400?, {0xc000d82800?, 0x742?}, {0xc000bf1c00?, 0xc0001fa3c0?, 0xc0018d8ea0?}, {0x1fafb40?, 0xba4cdfe?})
	/var/www/test/vendor/github.com/emmansun/gmsm/sm2/sm2.go:195 +0x3d
```

退回v0.26.1就正常  
go version go1.22.0 linux/amd64

**Comment by emmansun** [comment]
fix it in v0.27.2.

**Comment by kakuilan** [comment]
可以了，谢谢
