### ISSUE TITLE
SM9 ARM64 test fail

### ISSUE THREAD

**Issue by emmansun** [emmansun/gmsm#61]
=== RUN   Test_gfp12Gen
    bn_pair_test.go:56: not expected
--- FAIL: Test_gfp12Gen (0.01s)
=== RUN   Test_Pairing_A2
    bn_pair_test.go:66: not expected
--- FAIL: Test_Pairing_A2 (0.01s)
=== RUN   Test_Pairing_B2
    bn_pair_test.go:87: not expected
--- FAIL: Test_Pairing_B2 (0.01s)
=== RUN   Test_Pairing_B2_2
    bn_pair_test.go:101: not expected
--- FAIL: Test_Pairing_B2_2 (0.01s)
=== RUN   Test_finalExponentiation
    bn_pair_test.go:146: got (((4b5a0f5ff90fa92c62bfc03966907d70a5ab6b3dc19a6a8865593e43a82d258d, aa07bd07b8f029b3a1fd94a34e97fc650fefeb42ad86a5ec1979ff24bc1a1b11), (11554e7dee75253c2c41aa65c47c0cc21909c02e1aa800f9194d1e55ba25204b, 8602311b0e253f8ca8b0671ffe41296676a0df5aa0430d3936cd7287cdc7f394)), ((119aaf64404bcd37dd04d46d4a5610fb2c8b8846352369480f580930d1bacab2, aeb5d47b7231d14a51d48f521d7a9645e369dd19472f73c9c9461ea2194a8d4d), (311f62c61f7758f41d4e18d2a0c9781150f1b61cbf47d9dd5ee457b0bd858114, 0256efffe8875583c80bb5ac9a3922013e907e4bda5f54d466701464231ac584)), ((b520e00837db9507092b846caf84279ea4273110a40cf549175e8992bcd4ac15, 5f2266990cf25b5d64581fad0f6d058b1dab1a777dd5217f36d612e9b5d86883), (0adf5769e8367c758ec7d2032ee85ef15cb14eb8768d140fde9f18531c20d47e, 60f10107781302c5148c2c272b3f9f4396c4135aafafe0dc929dabee2a96a03c))), expected (((7f7d19d85f3602d345954a139354d3c21901e1a498d7450337c6871c7ed0ea64, 7b83e0ecad6e616e48b618729683f33e606c8ea9b073da6b2c3725791d45e8d8), (6ca7d15cbbaeb57c995123b041aca2f9ad23d6e3b7834c12e9c26a6af231d777, 9b29080b4e1e8e84bb7ea257c49c8488a3313d3bc3ca5d86dcfc5d312e7f622d)), ((b2028f6e33ce1c8f0f4b2ee0f2bdb6add1ea2b9d461e832c750cf2987107424f, 920641617a09ddabedef85f8f2894625dc563ec0333fe6d7c5e3e3a1985cfca3), (4d1eaf530e30ac1825cb388de9d4fea45abada079bd8cd79b6897e23c8b81f12, 2f8450b72e3e53a0c0abe3dd4422b93aefff6d8d585595b665a22d773dea48bc)), ((0d2492c399343534a0b49dda6750a135d766f7c23b05bdda2417bf81c4c4747c, 516eb30add5f91da3df80fb52c8469f82a7cb57b393332dc89c6ce9230eaa7e4), (67f12e4c84ef171a534b48da0413f857c0c7e0b3b905b3d6ea61430a858f11d3, 8fd6d693c9163c3715e94a0db5c47eec1cc6b406b6399537cac7bdee633fbf29)))
--- FAIL: Test_finalExponentiation (0.07s)
=== RUN   TestG1BaseMult
    g1_test.go:135: #1: got (69622fd48886da574b1df9391aec42c50019b4b2e1a88bd638359bd309c3b87f, 5d96360ee58a5a6840b3e8cad023e6c4081b3f91d70d7a811c4e9d44ac1c4f8e), want (98308a2cc761cd353d43546fb2f8b3a661d539acee2eee2f33347c295563f4b2, 5c8edf80776ea1ddca48a0cbb2fee68bd1ccbac88b2a814bc25b85d0d412a1fd)
    g1_test.go:135: #2: got (1acf86d2c34ff59240b13642673d0c3dc474a9584b36b1d74b5c5044b05b0ea1, 335542c9c812f1871fca0bebf4edc5a2e1585d3271f8284aff566f697f786f7a), want (6ac1f0dd2548250f9ca4a3926e98b10e294b3dca9f52a9be66f106a105602554, 71bbfd12e9a21877b25af9f5ab96b9178bc072871e7cf2491291c84942a70aee)
    g1_test.go:135: #3: got (aeb74f631a2caa4e2a536d2bc10327b9a8b3e4b34a9245b62d57b249637839b5, 4de0e1e2d8033a949ab5a2b4556950492cfce3e308708ef82e41702950a6feb), want (5f801a7846fd494756a2c774d3e70adc3dfe32a3eeee182440927290b335fce4, 90b13bf805932a7f7210c61f4d5dd59930b3ea816c5fe33c0c0e1b49c872066d)
    g1_test.go:135: #4: got (4b429937a9a8afd4275e6a3d546649f2362fb04156281c168d8ca024d24488d0, 51c7b11ea4018e2386e5f3950b58abe10298ac74f2bcddd5eeefbc8fb0b56c00), want (8a6ec5753ba604ef8c67b74cd00768826da871f8a8ec814c128975a979d27e16, 37a7cf29db07308c7cf9dd2c5b7865c84c062decc6fcf65e1a2fd69e194c8c76)
    g1_test.go:135: #5: got (4e83475f776ca1743d9a3b9a7b63e70f6d697abb55000af9153d7d78ec5d66ce, 603a403aba4247ad2abaf08fe69909cb4382a5b25d17782f744b6fc362767e02), want (2a6b8780b0bfe9d4e26a2cab6977904ec77fff42a41ce573431b0fc99741b470, 162b908e9ccbbbbcfa4b95194fc5be4cfbe1202e6d4b0cee0f1b6b108a5f7d1e)
    g1_test.go:135: #6: got (3a2152d1e9e2567c286f389a509a5b27c5e8df6842c6309564617795c2dca960, 5fac73c0a3c0265f2132a309a200b68b2bd96d1796a636e32ad3b154f7af68e), want (4e23307000bfdfa62183a3446649818889314051c95daf09dd2823b988e21dd9, 6f10a46330806c07d8acc529c98c3bccc724e471bb1b715d9ecacdd996f53070)
--- FAIL: TestG1BaseMult (0.00s)
=== RUN   TestFuzz
--- FAIL: TestFuzz (0.00s)
panic: sm9: ScalarMult was called on an invalid point [recovered]
	panic: sm9: ScalarMult was called on an invalid point

goroutine 12 [running]:
testing.tRunner.func1.1(0x1628e0, 0x1c7960)
	/home/travis/.gimme/versions/go1.15.15.linux.arm64/src/testing/testing.go:1072 +0x240
testing.tRunner.func1(0x4000001e00)
	/home/travis/.gimme/versions/go1.15.15.linux.arm64/src/testing/testing.go:1075 +0x34c
panic(0x1628e0, 0x1c7960)
	/home/travis/.gimme/versions/go1.15.15.linux.arm64/src/runtime/panic.go:969 +0x15c
github.com/emmansun/gmsm/sm9.(*G1Curve).ScalarMult(0x2a3bd0, 0x4000388060, 0x4000388080, 0x4000345f60, 0x20, 0x20, 0x4000434de0, 0x4000434e00)
	/home/travis/gopath/src/github.com/emmansun/gmsm/sm9/g1.go:342 +0x240
github.com/emmansun/gmsm/sm9.TestFuzz(0x4000001e00)
	/home/travis/gopath/src/github.com/emmansun/gmsm/sm9/g1_test.go:171 +0x1f0
testing.tRunner(0x4000001e00, 0x19eba0)
	/home/travis/.gimme/versions/go1.15.15.linux.arm64/src/testing/testing.go:1123 +0xdc
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.15.15.linux.arm64/src/testing/testing.go:1168 +0x244
FAIL	github.com/emmansun/gmsm/sm9	0.125s

**Comment by emmansun** [comment]
fix it in v0.13.1
