### ISSUE TITLE
CGO sm3 fatal error: invalid pointer found on stack

### ISSUE THREAD

**Issue by Trisia** [emmansun/gmsm#83]
项目中为了使用密码设备使用了CGO的程序在调用`CalculateZA`计算`ZA`，出现栈错误的问题，核心问题集中在 sm3函数wirte过程中。

错误栈如下：

```
runtime: bad pointer in frame crosstunnel/sys/security/dev/fm.(*DevSM2Key).Sign at 0xc0005657b0: 0x100
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw({0xfba5f9?, 0x18875c0?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7fb47f7fd698 sp=0x7fb47f7fd668 pc=0x43a77d
runtime.adjustpointers(0x7fb47f7fda98?, 0x260b52?, 0x163c894?, {0x18519d8?, 0x18875c0?})
        /usr/local/go/src/runtime/stack.go:630 +0x1d0 fp=0x7fb47f7fd700 sp=0x7fb47f7fd698 pc=0x452e30
runtime.adjustframe(0x7fb47f7fda98, 0x7fb47f7fdb88)
        /usr/local/go/src/runtime/stack.go:672 +0xc9 fp=0x7fb47f7fd790 sp=0x7fb47f7fd700 pc=0x452f49
runtime.gentraceback(0x0?, 0x0?, 0x0?, 0x0?, 0x0, 0x0, 0x7fffffff, 0x1022550, 0x0?, 0x0)
        /usr/local/go/src/runtime/traceback.go:334 +0xd0d fp=0x7fb47f7fdb00 sp=0x7fb47f7fd790 pc=0x45e1ed
runtime.copystack(0xc000417040, 0x800000002?)
        /usr/local/go/src/runtime/stack.go:932 +0x2f5 fp=0x7fb47f7fdcb8 sp=0x7fb47f7fdb00 pc=0x453755
runtime.newstack()
        /usr/local/go/src/runtime/stack.go:1112 +0x497 fp=0x7fb47f7fde70 sp=0x7fb47f7fdcb8 pc=0x453cd7
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:570 +0x8b fp=0x7fb47f7fde78 sp=0x7fb47f7fde70 pc=0x46974b

goroutine 116 [copystack]:
github.com/emmansun/gmsm/sm3.block(0xc0005655e8, {0xc000565608, 0x40, 0x40})
        /home/kkk/go/pkg/mod/github.com/emmansun/gmsm@v0.14.1/sm3/sm3block_amd64.s:896 +0x7214 fp=0xc000565568 sp=0xc000565560 pc=0x5c8714
github.com/emmansun/gmsm/sm3.(*digest).Write(0xc0005655e8, {0xc0006cea60, 0x20, 0x20})
        /home/kkk/go/pkg/mod/github.com/emmansun/gmsm@v0.14.1/sm3/sm3.go:169 +0xd7 fp=0xc0005655c0 sp=0xc000565568 pc=0x5c12d7
github.com/emmansun/gmsm/sm2.calculateZA(0xc00044ada0, {0x186fad0, 0x10, 0x10})
        /home/kkk/go/pkg/mod/github.com/emmansun/gmsm@v0.14.1/sm2/sm2.go:721 +0x20b fp=0xc0005656b0 sp=0xc0005655c0 pc=0x5cf4ab
github.com/emmansun/gmsm/sm2.CalculateZA(...)
        /home/kkk/go/pkg/mod/github.com/emmansun/gmsm@v0.14.1/sm2/sm2.go:704
crosstunnel/sys/security/dev/fm.(*DevSM2Key).PHash(0x7fb4ebb33108?, 0x40?, {0xc00180e6c0, 0x237, 0x240}, {0x0?, 0x203000?, 0x203000?})
        /mnt/d/Project/vpn/crosstunnel/sys/security/dev/fm/sm2.go:100 +0x72 fp=0xc000565750 sp=0xc0005656b0 pc=0xddaf12
crosstunnel/sys/security/dev/fm.(*DevSM2Key).Sign(0xc000a2a468, {0xf2b980?, 0xc000a2a468?}, {0xc00180e6c0, 0x237, 0x240}, {0x7fb4ebb3e5c0?, 0xc0006ce980?})
        /mnt/d/Project/vpn/crosstunnel/sys/security/dev/fm/sm2.go:67 +0xb7 fp=0xc000565880 sp=0xc000565750 pc=0xdda857
gitee.com/Trisia/gotlcp/tlcp.(*eccKeyAgreement).generateServerKeyExchange(0xc000840101?, 0xc000402480?)
        /home/kkk/go/pkg/mod/gitee.com/!trisia/gotlcp@v1.1.4/tlcp/key_agreement.go:101 +0x17b fp=0xc000565948 sp=0xc000565880 pc=0x6a637b
gitee.com/Trisia/gotlcp/tlcp.(*serverHandshakeState).doFullHandshake(0xc0006c40a0)
        /home/kkk/go/pkg/mod/gitee.com/!trisia/gotlcp@v1.1.4/tlcp/handshake_server.go:408 +0x590 fp=0xc000565bf8 sp=0xc000565948 pc=0x6a3cf0
gitee.com/Trisia/gotlcp/tlcp.(*serverHandshakeState).handshake(0xc0006c40a0)
        /home/kkk/go/pkg/mod/gitee.com/!trisia/gotlcp@v1.1.4/tlcp/handshake_server.go:98 +0x125 fp=0xc000565c30 sp=0xc000565bf8 pc=0x6a1f85
gitee.com/Trisia/gotlcp/tlcp.(*Conn).serverHandshake(0xc00040d340, {0x114b000, 0xc000a1c740})
        /home/kkk/go/pkg/mod/gitee.com/!trisia/gotlcp@v1.1.4/tlcp/handshake_server.go:64 +0xf0 fp=0xc000565c68 sp=0xc000565c30 pc=0x6a1e10
gitee.com/Trisia/gotlcp/tlcp.(*Conn).serverHandshake-fm({0x114b000?, 0xc000a1c740?})
        <autogenerated>:1 +0x39 fp=0xc000565c90 sp=0xc000565c68 pc=0x6a9859
gitee.com/Trisia/gotlcp/tlcp.(*Conn).handshakeContext(0xc00040d340, {0x114b038, 0xc00003a3e8})
        /home/kkk/go/pkg/mod/gitee.com/!trisia/gotlcp@v1.1.4/tlcp/conn.go:1210 +0x32f fp=0xc000565e58 sp=0xc000565c90 pc=0x69d6cf
gitee.com/Trisia/gotlcp/tlcp.(*Conn).HandshakeContext(...)
        /home/kkk/go/pkg/mod/gitee.com/!trisia/gotlcp@v1.1.4/tlcp/conn.go:1153
gitee.com/Trisia/gotlcp/tlcp.(*Conn).Handshake(...)
        /home/kkk/go/pkg/mod/gitee.com/!trisia/gotlcp@v1.1.4/tlcp/conn.go:1137
gitee.com/Trisia/gotlcp/tlcp.(*Conn).Read(0xc00040d340, {0xc00180d000, 0x1000, 0xc0008ba360?})
        /home/kkk/go/pkg/mod/gitee.com/!trisia/gotlcp@v1.1.4/tlcp/conn.go:1028 +0x65 fp=0xc000565ec8 sp=0xc000565e58 pc=0x69cb85
crosstunnel/sys/tcpproxy.trans({0x11449a0, 0xc0006c80d8}, {0x7fb4c00b0f88, 0xc00040d340}, 0xc0006dfde8)
        /mnt/d/Project/vpn/crosstunnel/sys/tcpproxy/worker.go:143 +0x117 fp=0xc000565f78 sp=0xc000565ec8 pc=0xc88997
crosstunnel/sys/tcpproxy.(*worker).handler.func2()
```

关键代码如下：

```go
func (d *DevSM2Key) Public() crypto.PublicKey {
       // 从密码设备中获取公钥...
	x := C.GoBytes(unsafe.Pointer(&pubKey.x[0]), 32)
	y := C.GoBytes(unsafe.Pointer(&pubKey.y[0]), 32)
	d.pub = &ecdsa.PublicKey{
		Curve: sm2.P256(),
		X:     new(big.Int).SetBytes(x),
		Y:     new(big.Int).SetBytes(y),
	}
```

故障发生于,Cgo得到的公钥在计算Phash过程中的`CalculateZA`

```go
func (d *DevSM2Key) PHash(pub *ecdsa.PublicKey, msg, uid []byte) ([]byte, error) {
	if len(uid) == 0 {
		uid = _DefaultUID
	}
	za, err := sm2.CalculateZA(pub, uid)
	if err != nil {
		return nil, err
	}
	// 预处理2
	h := sm3.New()
	h.Write(za)
	h.Write(msg)
	return h.Sum(nil)[:32], nil
}
```

**Comment by emmansun** [comment]
你尝试在Public()方法返回一个正确的普通sm2公钥试试。

**Comment by emmansun** [comment]
另外，最好用```Unmarshal(sm2.P256(), 0x04 || x_bytes || y_bytes)```方法，来反序列化x, y, 这样可以检查x, y的正确性。

**Comment by Trisia** [comment]
> 你尝试在Public()方法返回一个正确的普通sm2公钥试试。

我尝试完全使用Go的内存如下:

```go
func (d *DevSM2Key) Public() crypto.PublicKey {
	x, _ := hex.DecodeString("0EF5238D77486CF03B6F276AC21CECA6834AAD5CC4C3161E1E19100B58D26ED4")
	y, _ := hex.DecodeString("184264F0826AF4EB5D147782B6F3403B44B7C606302562E45532731528650C91")
	return &ecdsa.PublicKey{
		Curve: sm2.P256(),
		X:     new(big.Int).SetBytes(x),
		Y:     new(big.Int).SetBytes(y),
	}
}
```

问题依旧存在。

该问题确实较为诡异，当我同一对密钥对仅使用一个TLCP服务时，没有任何异样。

但我将原来的tlcp.Config复制之后启动新的TLCP服务时，在新的TLCP服务中就会出现该问题，而且该问题是不可恢复的，每次发生都导致进程崩溃。

如上文所属，我将整个公钥都预置了，但是PHash在调用`sm2.CalculateZA` 依然会在  `sm3.Write` 时发生异常。

我曾单独将该业务拆解出来，均未能重现。

因此我对PHash代码进行了重写，使用SDF密码设备SM3接口来完成的PHash功能，该问题就消失了。

推测可能是业务中某处没有处理好内存关系？

**Comment by emmansun** [comment]
可以尝试编译一下generic版本试试。

**Comment by Trisia** [comment]
我在编译参数上添加了

```bash
go build -tags generic -ldflags '-s -w' -o app
```

结果没有改变，该问题我认为可能是由于我自己没有处理好并发以及内存关系导致。
```
runtime: bad pointer in frame crosstunnel/sys/security/dev/fm.(*DevSM2Key).Sign at 0xc000beb770: 0x100
fatal error: invalid pointer found on stack

runtime stack:
runtime.throw({0xf929e8?, 0x1846580?})
        /usr/local/go/src/runtime/panic.go:1047 +0x5d fp=0x7f95c7ffe698 sp=0x7f95c7ffe668 pc=0x43a77d
runtime.adjustpointers(0x7f95c7ffea98?, 0x25fc31?, 0x15fdad3?, {0x1811298?, 0x1846580?})
        /usr/local/go/src/runtime/stack.go:630 +0x1d0 fp=0x7f95c7ffe700 sp=0x7f95c7ffe698 pc=0x452e30
runtime.adjustframe(0x7f95c7ffea98, 0x7f95c7ffeb88)
        /usr/local/go/src/runtime/stack.go:672 +0xc9 fp=0x7f95c7ffe790 sp=0x7f95c7ffe700 pc=0x452f49
runtime.gentraceback(0x0?, 0x0?, 0x0?, 0x0?, 0x0, 0x0, 0x7fffffff, 0xfe5130, 0x0?, 0x0)
        /usr/local/go/src/runtime/traceback.go:334 +0xd0d fp=0x7f95c7ffeb00 sp=0x7f95c7ffe790 pc=0x45e1ed
runtime.copystack(0xc00072a4e0, 0x800000002?)
        /usr/local/go/src/runtime/stack.go:932 +0x2f5 fp=0x7f95c7ffecb8 sp=0x7f95c7ffeb00 pc=0x453755
runtime.newstack()
        /usr/local/go/src/runtime/stack.go:1112 +0x497 fp=0x7f95c7ffee70 sp=0x7f95c7ffecb8 pc=0x453cd7
runtime.morestack()
        /usr/local/go/src/runtime/asm_amd64.s:570 +0x8b fp=0x7f95c7ffee78 sp=0x7f95c7ffee70 pc=0x46974b

goroutine 103 [copystack]:
github.com/emmansun/gmsm/sm3.blockGeneric(0xc000beb4f8, {0xc000beb518?, 0x40?, 0x40?})
        /home/kkk/go/pkg/mod/github.com/emmansun/gmsm@v0.14.1/sm3/sm3block.go:26 +0x617 fp=0xc000beb3b0 sp=0xc000beb3a8 pc=0x5c4ed7
github.com/emmansun/gmsm/sm3.block(...)
        /home/kkk/go/pkg/mod/github.com/emmansun/gmsm@v0.14.1/sm3/sm3block_generic.go:7
github.com/emmansun/gmsm/sm3.(*digest).Write(0xc000beb4f8, {0xc000beb450, 0x8, 0x40})
        /home/kkk/go/pkg/mod/github.com/emmansun/gmsm@v0.14.1/sm3/sm3.go:169 +0xc5 fp=0xc000beb408 sp=0xc000beb3b0 pc=0x5c46e5
github.com/emmansun/gmsm/sm3.(*digest).checkSum(0xc000beb4f8)
        /home/kkk/go/pkg/mod/github.com/emmansun/gmsm@v0.14.1/sm3/sm3.go:142 +0xe9 fp=0xc000beb4a0 sp=0xc000beb408 pc=0x5c4549
github.com/emmansun/gmsm/sm3.(*digest).Sum(0xc00078c5a8?, {0x0, 0x0, 0x0})
        /home/kkk/go/pkg/mod/github.com/emmansun/gmsm@v0.14.1/sm3/sm3.go:125 +0x65 fp=0xc000beb580 sp=0xc000beb4a0 pc=0x5c4365
github.com/emmansun/gmsm/sm2.calculateZA(0xc000447000, {0x182eae0, 0x10, 0x10})
        /home/kkk/go/pkg/mod/github.com/emmansun/gmsm@v0.14.1/sm2/sm2.go:726 +0x309 fp=0xc000beb670 sp=0xc000beb580 pc=0x5cbdc9
github.com/emmansun/gmsm/sm2.CalculateZA(...)
        /home/kkk/go/pkg/mod/github.com/emmansun/gmsm@v0.14.1/sm2/sm2.go:704
crosstunnel/sys/security/dev/fm.(*DevSM2Key).PHash(0x100000000?, 0x50e4de?, {0xc000b426c0, 0x237, 0x240}, {0x0?, 0x5?, 0x0?})
        /mnt/d/Project/vpn/crosstunnel/sys/security/dev/fm/sm2.go:105 +0x72 fp=0xc000beb710 sp=0xc000beb670 pc=0xdb3812
```

**Comment by Trisia** [comment]
由于没有复现的简单代码和设备运行环境，我认为您这边可能确实较为难以处理该问题，我空时候再探索一下吧，感谢！

**Comment by Trisia** [comment]
原因找到了

我再go中使用cgo申请了 一部分内存存储在一个指针中（由go管理）

该指针在go gc时被被移动到了其他位置导致，空指针。

我将该指针迁移至 C的内存管理后，问题得到解决。
